stages:
  clean-data:
    cmd: python3 scripts/data_scripts/clean_data.py data/raw/cars.csv
    deps:
    - data/raw/cars.csv
    - scripts/data_scripts/clean_data.py
    outs:
    - data/stage1
  get-features:
    cmd: python3 scripts/data_scripts/get_features.py data/stage1/cars.csv
    deps:
    - data/stage1/cars.csv
    - scripts/data_scripts/get_features.py
    outs:
    - data/stage2
  split:
    cmd: python3 scripts/data_scripts/train_test_split.py data/stage2/cars.csv
    deps:
    - data/stage2/cars.csv
    - scripts/data_scripts/train_test_split.py
    params:
    - split.seed
    - split.split_ratio
    outs:
    - data/stage3
