stages:
  clean-data:
    cmd: python3 scripts/data_scripts/clean_data.py data/raw/cars.csv
    deps:
    - data/raw/cars.csv
    - scripts/data_scripts/clean_data.py
    outs:
    - data/stage1
  get-features:
    cmd: python3 scripts/data_scripts/get_features.py data/stage1/cars.csv
    deps:
    - data/stage1/cars.csv
    - scripts/data_scripts/get_features.py
    outs:
    - data/stage2
